services:
  - type: web
    name: ocr-api
    env: python3
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
